# Generated by Django 4.1.6 on 2023-02-12 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Нименование товара')),
                ('description', models.CharField(max_length=100, verbose_name='Описание')),
                ('price', models.PositiveBigIntegerField(default=0, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Номер счета')),
                ('amount', models.PositiveBigIntegerField(default=0, verbose_name='Количество')),
                ('state', models.BooleanField(default=False, verbose_name='Оплачен')),
                ('product_to_pay', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pay_service.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Счет',
                'verbose_name_plural': 'Счета',
            },
        ),
    ]
